apiVersion: batch/v1
kind: Job
metadata:
  name: conbench-migration
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: conbench-migration
        image: "{{CONBENCH_SERVER_IMAGE_SPEC}}"
        command: ["/usr/local/bin/conbench", "migrate"]
        envFrom:
          - configMapRef:
              name: conbench-config
          - secretRef:
              name: conbench-secret
        resources:
          requests:
            # Pretend that we don't need resources, so that node placement
            # succeeds even on small-resource k8s clusters.
            memory: '1Mi'
            cpu: 1m
      restartPolicy: Never
